# Set initial window size
window:
  dimensions:
    columns: 125
    lines: 35

# Font configuration
font:
  size: 16.0

# Bindings for: jump f/b by words
key_bindings:
  - { key: B, mods: Alt, chars: "\x1bb" }
  - { key: F, mods: Alt, chars: "\x1bf" }
  - { key: Left, mods: Alt, chars: "\x1bb" }
  - { key: Right, mods: Alt, chars: "\x1bf" }

# VSCode's integrated terminal default colors
# Primary and dimmed colors needed
colors:
  # Default colors
  primary:
    background: '#1e1e1e' #Background from Dark Theme

  # Normal colors
  normal:
    black:   '#000000'
    red:     '#cd3131'
    green:   '#0dbc79'
    yellow:  '#e5e510'
    blue:    '#2472c8'
    magenta: '#bc3fbc'
    cyan:    '#11a8cd'
    white:   '#e5e5e5'

  # Bright colors
  bright:
    black:   '#666666'
    red:     '#f14c4c'
    green:   '#23d18b'
    yellow:  '#f5f543'
    blue:    '#3b8eea'
    magenta: '#d670d6'
    cyan:    '#29b8db'
    white:   '#e5e5e5'
